### ISSUE TITLE
채용 상세 페이지 조회 기능 구현

### ISSUE THREAD

**Issue by irerin07** [irerin07/wanted-pre-onboarding-backend#10]
### 요구 사항

1. 유저는 채용공고의 **상세 페이지를 조회**할 수 있어야 한다.
2. 상세 페이지 **조회 시 전달되는 정보**는 다음과 같다
    1. 채용공고 id (**유저에겐 보이지 않는다**)
    2. 회사 명
    3. 국가
    4. 지역
    5. 채용 포지션
    6. 채용 포상금
    7. 사용 기술
    8. 채용 내용
    9. 회사가 올린 다른 채용 공고
        1. 다른 채용 공고 id의 List

### TODO

- [x]  상세 페이지 조회용 API 구현
- [x]  상세 페이지 조회 서비스 메서드 구현
- [x]  상세 페이지 조회 레포지토리 메서드 구현
- [x]  응답 객체 생성
