### ISSUE TITLE
채용 공고 지원

### ISSUE THREAD

**Issue by irerin07** [irerin07/wanted-pre-onboarding-backend#14]
### 요구 사항

1. 지원자는 시스템에 등록된 **채용공고 중 삭제되지 않은 채용공고에 한하여 지원**할 수 있어야 한다.
2. 지원자가 채용공고에 지원 시 전달받은 지원자의 **사용자 id와 채용공고 id를 기반으로 지원 히스토리**를 남겨야 한다.
    1. 지원시 지원한 날짜를 입력해야 한다.
3. 지원자가 해당 채용 공고에 지원 이력이 있는 경우 더는 지원할 수 없다. 즉, **한 채용 공고당 최대 1회 지원이 가능**하다.

### TODO

- [x]  지원 API 생성
    - [x]  ApplyController
- [x]  지원 서비스 생성
    - [x]  ApplyHistoryService
- [x]  레포지토리 생성
    - [x]  ApplyHistoryRepository
- [x]  유효한 채용 공고인지 체크
- [x]  지원 이력이 있는지 체크
    - [x]  없다면 지원 이력 저장
    - [x]  있다면 예외처리
