### ISSUE TITLE
채용 공고 삭제시 회사 id 불필요

### ISSUE THREAD

**Issue by irerin07** [irerin07/wanted-pre-onboarding-backend#17]
### 요구사항

- 채용 공고 삭제기 회사 id를 path variable로 받고 있는 상태이지만 불필요하다 판단되어 삭제

### TODO

- [x]  controller path variable 삭제
- [x]  서비스에서 회사 id 파라미터로 넘겨 받는 것 삭제
- [x]  회사 id로 조회하는 메소드 처리
